WebApp/Pages/Ticket/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using Domain;

namespace WebApp.Pages.Ticket
{
    public class CreateModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public CreateModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Domain.Ticket Ticket { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Ticket.CreatedAtDt=DateTime.Now;

            _context.Tickets.Add(Ticket);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Ticket/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Ticket
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public DeleteModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Domain.Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);

            if (ticket == null)
            {
                return NotFound();
            }
            else
            {
                Ticket = ticket;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            var finished = false;
            if (ticket != null)
            {
                Ticket = ticket;
                finished = ticket.IsDone;
                _context.Tickets.Remove(Ticket);
                await _context.SaveChangesAsync();
            }

            if (finished)
            {
                return RedirectToPage("./FinishedTickets"); 
            }
            else
            {
                return RedirectToPage("./Index");
            }

            
        }
    }
}

WebApp/Pages/Ticket/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Ticket
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public DetailsModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        public Domain.Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }
            else
            {
                Ticket = ticket;
            }
            return Page();
        }
    }
}

WebApp/Pages/Ticket/DetailsFinished.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Ticket;

public class DetailsFinished : PageModel
{
    private readonly DAL.AppDbContext _context;

    public DetailsFinished(DAL.AppDbContext context)
    {
        _context = context;
    }

    public Domain.Ticket Ticket { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
        if (ticket == null)
        {
            return NotFound();
        }
        else
        {
            Ticket = ticket;
        }
        return Page();
    }
}

WebApp/Pages/Ticket/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Ticket
{
    public class EditModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public EditModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Domain.Ticket Ticket { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket =  await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }
            
            Ticket = ticket;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var existingTicket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == Ticket.Id);
            if (existingTicket == null)
            {
                return NotFound();
            }

            // Retain the original CreatedAtDt value
            var originalCreatedAt = existingTicket.CreatedAtDt;

            // Update the properties that can change
            existingTicket.Name = Ticket.Name;
            existingTicket.Description = Ticket.Description;
            existingTicket.FinishedBy = Ticket.FinishedBy;
            existingTicket.IsDone = Ticket.IsDone;

            // Restore the original CreatedAtDt value
            existingTicket.CreatedAtDt = originalCreatedAt;
            existingTicket.UpdatedAt = DateTime.Now;

            // Mark the ticket as modified
            _context.Entry(existingTicket).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(Ticket.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TicketExists(Guid id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

WebApp/Pages/Ticket/FinishedTickets.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Pages.Ticket;

public class FinishedTickets : PageModel
{
        private readonly DAL.AppDbContext _context;

        public FinishedTickets(DAL.AppDbContext context)
        {
            _context = context;
        }

        public IList<Domain.Ticket> Ticket { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Ticket = await _context.Tickets
                .OrderByDescending(t => t.FinishedBy) 
                .ToListAsync();
        }
}

WebApp/Pages/Ticket/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages.Ticket
{
    public class IndexModel : PageModel
    {
        private readonly DAL.AppDbContext _context;

        public IndexModel(DAL.AppDbContext context)
        {
            _context = context;
        }

        public IList<Domain.Ticket> Ticket { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Ticket = await _context.Tickets
                .OrderByDescending(t => t.FinishedBy) 
                .ToListAsync();
        }
        public async Task<IActionResult> OnPostMarkAsDone(Guid id)
        {
            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }

            ticket.IsDone = true;
            ticket.UpdatedAt = DateTime.Now;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/Ticket/Create.cshtml
@page
@model WebApp.Pages.Ticket.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Ticket name</label>
                <input asp-for="Ticket.Name" class="form-control" />
                <span asp-validation-for="Ticket.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <textarea asp-for="Ticket.Description" class="form-control"></textarea>
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Finished by</label>
                <input asp-for="Ticket.FinishedBy" class="form-control" />
                <span asp-validation-for="Ticket.FinishedBy" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Pages/Ticket/Delete.cshtml
@page
@model WebApp.Pages.Ticket.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Created at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedAtDt)
        </dd>
        <dt class="col-sm-2">
            Updated at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.UpdatedAt)
        </dd>
        <dt class="col-sm-2">
            Ticket name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
        <dt class="col-sm-2">
            Finishing time
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.FinishedBy)
        </dd>
        <dt class="col-sm-2">
            Is the ticket done?
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.IsDone)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Ticket.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

WebApp/Pages/Ticket/Details.cshtml
@page
@model WebApp.Pages.Ticket.DetailsModel

@{
    ViewData["Title"] = "Details";
}

@{
    TimeSpan timeDifference = Model.Ticket.FinishedBy - DateTime.Now;
    int remainingDays = (int)timeDifference.TotalDays;
    int remainingHours = timeDifference.Hours;
    int remainingMinutes = timeDifference.Minutes;
}

<h1>Details</h1>

<div>
    <h4>Ticket #@Model.Ticket.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Created at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedAtDt)
        </dd>
        <dt class="col-sm-2">
            Updated at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.UpdatedAt)
        </dd>
        <dt class="col-sm-2">
            Ticket name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
        <dt class="col-sm-2">
            Finishing time
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.FinishedBy)
        </dd>
        <dt class="col-sm-2">
            Is the ticket done?
        </dt>
        <dd class="col-sm-10">
            @(Model.Ticket.IsDone ? "Yes" : "No")
        </dd>
        <dt class="col-sm-2">
            Remaining Time
        </dt>
        <dd class="col-sm-10">
            @if (remainingDays > 0)
            {
                <span>@remainingDays day(s), </span> 
            }
            <span>@remainingHours</span> hour(s), 
            <span>@remainingMinutes</span> minute(s)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Ticket.Id">Edit</a> |
    <a asp-page="./Delete" asp-route-id="@Model.Ticket.Id">Delete</a> |
    <a asp-page="./Index">Back to List</a>
</div>

WebApp/Pages/Ticket/DetailsFinished.cshtml
@page
@model WebApp.Pages.Ticket.DetailsFinished

@{
    ViewData["Title"] = "Details";
}

@{
    TimeSpan timeDifference = Model.Ticket.FinishedBy - Model.Ticket.UpdatedAt;
    int remainingDays = (int)timeDifference.TotalDays;
    int remainingHours = timeDifference.Hours;
    int remainingMinutes = timeDifference.Minutes;
}

<h1>Details</h1>

<div>
    <h4>Finished Ticket #@Model.Ticket.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Created at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.CreatedAtDt)
        </dd>
        <dt class="col-sm-2">
            Finished at
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.UpdatedAt)
        </dd>
        <dt class="col-sm-2">
            Ticket name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Name)
        </dd>
        <dt class="col-sm-2">
            Ticket description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.Description)
        </dd>
        <dt class="col-sm-2">
            Finishing time
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ticket.FinishedBy)
        </dd>
        <dt class="col-sm-2">
            Is the ticket done?
        </dt>
        <dd class="col-sm-10">
            @(Model.Ticket.IsDone ? "Yes" : "No")
        </dd>
        <dt class="col-sm-2">
            Remaining Time
        </dt>
        <dd class="col-sm-10">
            @if (remainingDays > 0)
            {
                <span>@remainingDays day(s), </span> 
            }
            <span>@remainingHours</span> hour(s), 
            <span>@remainingMinutes</span> minute(s)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-page="./Delete" asp-route-id="@Model.Ticket.Id">Delete</a> |
    <a asp-page="./FinishedTickets">Back to Finished Tickets List</a>
</div>

WebApp/Pages/Ticket/Edit.cshtml
@page
@model WebApp.Pages.Ticket.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Ticket name</label>
                <input asp-for="Ticket.Name" class="form-control" />
                <span asp-validation-for="Ticket.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ticket.Description" class="control-label"></label>
                <textarea asp-for="Ticket.Description" class="form-control"></textarea>
                <span asp-validation-for="Ticket.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Finished by</label>
                <input asp-for="Ticket.FinishedBy" class="form-control" />
                <span asp-validation-for="Ticket.FinishedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ticket.IsDone" /> @Html.DisplayNameFor(model => model.Ticket.IsDone)
                </label>
            </div>
            <input type="hidden" asp-for="Ticket.Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a> | <a asp-page="./Delete" asp-route-id="@Model.Ticket.Id">Delete</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Pages/Ticket/FinishedTickets.cshtml
@page
@model WebApp.Pages.Ticket.FinishedTickets

@{
    ViewData["Title"] = "Index";
}
<head>
    <title>Active Tickets</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<h1>Finished tickets</h1>

<p>
    <a asp-page="Create">Create New Ticket</a> | <a asp-page="Index">Active Tickets</a> 
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            Created at
        </th>
            
        <th>
            Ticket name
        </th>
        <th>
            Ticket description
        </th>
        <th>
            Finishing time
        </th>
           
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Ticket) {
        if (item.IsDone)
        {
            var shortDescription = item.Description.Length > 50 ? item.Description.Substring(0, 50) + "..." : item.Description;
            <tr >
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAtDt)
                </td>
            
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @shortDescription
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedAt)
                </td>
            
                <td>
                    <a asp-page="./DetailsFinished" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
        
    }
    </tbody>
</table>

WebApp/Pages/Ticket/Index.cshtml
@page
@model WebApp.Pages.Ticket.IndexModel

@{
    ViewData["Title"] = "Index";
}
<head>
    <title>Active Tickets</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<h1>Active tickets</h1>

<p>
    <a asp-page="Create">Create New Ticket</a> | <a asp-page="FinishedTickets">Finished Tickets</a> 
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Created at
            </th>
            
            <th>
                Ticket name
            </th>
            <th>
                Ticket description
            </th>
            <th>
                Finishing time
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Ticket) {
    if (!item.IsDone)
    {
        var timeDifference = (item.FinishedBy - DateTime.Now).TotalHours;
        var cssClass = timeDifference < 1 ? "urgent" : "";
        var shortDescription = item.Description.Length > 50 ? item.Description.Substring(0, 50) + "..." : item.Description;
        <tr class="@cssClass">
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAtDt)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @shortDescription
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishedBy)
            </td>
            
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                <form method="post" asp-page-handler="MarkAsDone">
                    <input type="hidden" name="id" value="@item.Id" />
                    <button type="submit" class="pretty-button">Mark as Done</button>
                </form>
            </td>
        </tr>
    }
        
}
    </tbody>
</table>